### ISSUE TITLE
Add "templates update" command

### ISSUE THREAD

**Issue by larryfenn** [associatedpress/datakit-project#3]
Create a `project templates update` command that triggers an interactive prompt allowing user to update one or more templates. 

Tasks:

- [x] Add a help flag and/or default help text that notifies the user how to get the current status of templates via the `templates --status` command (#22)
- [x] Add an interactive prompt that allows user to choose a single, multiple or all templates for update
- [x] Update `templates --status` help text with mention of `templates update` command

We should be able to implement this using Cookiecutter's [clone function](https://github.com/audreyr/cookiecutter/blob/3bc7b987e4ae9dcee996ae0b00375c1325b8d866/cookiecutter/vcs.py#L59), possibly with some light modification or extension. Should review CC's cli.py module to see how it is applied before finalizing implementation.

## Original ticket write-up

> Below are contents of original ticket.

We have changed cookiecutter-r-project; however, template update availability is not obvious.

Without knowing how much work might be involved implementing this functionality, here are two ideas:

Proposition 1:
If there are updated templates, tell the user that updates are available, and have a separate update command. I'm thinking something like how `pip` works for users.
- On `datakit project create`, check to see if (any|current template being used) has been updated, and if so alert the user ("Template x-y-z-cookiecutter is not the most recent") and offer a choice of what to do next (abort, update and continue).
- Separately, have an update command that will do the job of updating.

Proposition 2:
Always keep templates up to date. Any time datakit is run, it checks if templates are up to date, and if not grabs the latest.

**Comment by zstumgoren** [comment]
+1 to a variation of Proposition 1

I'd like to keep the `project:create` implementation "simple" in the sense that once a template is installed, there's no need to hit a remote Github location. Everything happens locally. You can update a template by specifying the template again when you create a new project, but as you mention, this is a non-obvious feature.

To provide more robust/explicit support for managing templates, we can add an explicit command that checks for updates on one, multiple or all projects. And separately, as you suggest, we can have a command to update one, multiple or all templates.

* `project:check_for_template_updates` (*not in love with the name, but you get the idea*)
* `project:update_templates` with two flags:
  * `--templates`  accepts one or more names
  * `--all` updates all templates (mutually exclusive wrt `--templates` flag)

Let's steer clear of Prop. 2 since it could catch folks off-guard by triggering updates they may not want. They may not notice command-line alerts about any updates, and if they do, they'd still be on the hook to manually roll back changes.

**Comment by larryfenn** [comment]
Guessing that updating templates might not be a common/frequent occurrence, would it be best to just fold all of this into one command?

`project:update_templates`: if run by itself, does a check for updates and responds with either "all templates up to date" or "templates X, Y, and Z have been updated; run command `project:update_templates X` to update template X

`project:update_templates X`: attempts to update template X.

**Comment by zstumgoren** [comment]
I'd like to keep retrieval of info about a template separate from the act of updating the template because of a few goodies I have planned for these actions.

For example, the template-status command will provide info in either short or detailed forms, where the latter lists all available branches and/or tags. That detailed info will tie in nicely with support in the update command to install from branches, tags and commit IDs (*see #1*).

## Commands (redux)

Here's a refined version of the two commands that reflects above considerations and (hopefully) more human-friendly semantics. 

* `project:templates` - List installed templates (#2) with brief info (e.g. name and commit ID)
* `project:templates:info` - Provide detailed info about one or more templates
  * **with no arguments** lists detailed info about all installed templates
  *  *cookiecutter-foo, cookiecutter-bar, etc.* - List detailed info about specified templates supplied as unnamed args
* `project:templates:update` - Updates one or more projects
  * **with no arguments or flags** - does nothing; dumps Help message to stdout
  * *cookiecutter-foo, cookiecutter-bar, etc.* - Update projects specified as unnamed args.
  * `--all` - Update all templates.

## Projects prefix?

Should we drop the `project` prefix from the commands above and instead do something like this?

* `templates:list`
* `templates:info`
* `templates:update`

While the `project` prefix signals that these commands belong with the `datakit-project` plugin, doesn't seem very friendly from an end-user perspective (guessing you all care more about finding these commands in a sensible place rather than remembering which plugin they're packaged with). 

I'm kind of leaning toward dropping `project` prefix, but let me know your thoughts.

**Comment by larryfenn** [comment]
I like the organization of `templates` (for high level info), with `templates:info` and `templates:update` as commands to go deeper.

Dropping the prefix is probably not a huge deal- it looks unwieldy to do `datakit project:templates:info` but aside from the initial period of using a template I don't think there will frequently be a rush of changes or updates that need to happen.

For fear of choosing the worst of both worlds- would aliasing `datakit templates` to `datakit project:templates` be a horrible idea?

**Comment by zstumgoren** [comment]
+1 to aliasing. That's very easy to do with the plugin strategy we're using. I'll plan to do that and we could always undo one or the other if folks think the command list is too cluttered.

**Comment by zstumgoren** [comment]
Updated ticket description with implementation plans

**Comment by zstumgoren** [comment]
`templates update` implemented as an interactive command with extra help text.
