### ISSUE TITLE
Rename command

### ISSUE THREAD

**Issue by larryfenn** [associatedpress/datakit-project#5]
The project folder as well as all the `cookiecutter` files use the project name. In the instance where we want to change the project name after the fact, a script should change all of these to the new name.

For example, with the R project cookiecutter, the .Rproj file has to be changed to have the same name as the project.

**Comment by zstumgoren** [comment]
@larryfenn Can you provide some more details on this? For example a simple before/after file tree showing the file and directory artifacts that would need to change?

If I'm understanding this right, it may be tricky to devise a generally applicable solution, since end users of this plugin can have any number of Cookiecutter templates. Given that, the renaming convention would likely be idiosyncratic to each Cookiecutter template.

If this is something specific to AP's workflow, it might make sense to implement this in a new AP plugin or a fork of this project.

If you can provide more details, we can separate out the general from the AP-specific bits and devise a plan of attack.

**Comment by larryfenn** [comment]
I didn't realize this would have issues with the arbitrary cookiecutter templates people could be using. I was thinking originally it would just be a renaming script that goes through and replaces every instance of cookiecutter.project_slug with a replacement text. For example, in a published project:

- the project folder itself
- the .Rproj file (here, generated by cookiecutter-r-project)
- the s3 path in config/datakit-data.json
- the data.world slug in config/datakit-dworld.json

In this case, I will say that there's some complication here:
- changing the s3 path might break some external links we may have done to RMarkdown reports
- changing the data.world slug will definitely break access (if it's already been shared with members)

Maybe this isn't worth it at the moment -- even something lightweight like a list of items that depend on cookiecutter.project_slug wouldn't really be useful to anyone, since people who would be interested in doing a manual rename can probably seek out and identify all instances of their project slug in the data, and people who would like to do a rename operation but need help with it aren't going to have easy guidance with just a list of files.

**Comment by zstumgoren** [comment]
Thanks for the detailed clarification. It does indeed sound like potentially tricky ground for the AP use case, especially after a project has gone live on various services. On the whole though, this sounds like the kind of thing that might be worth considering as part of an AP-specific plugin, since the services you mention (S3, Data.world) are highly specific to AP.  It could be possible to build out a plugin, for example, that includes safety checks as part of an interactive renaming process (e.g. determining if a project is already live on data.world or at least asking the user to verify this before proceeding). But yeah, I think this would generally be out of scope for this one little plugin :)

I'm going to close this ticket for now, but feel free to re-open if you have any objections.
